server:
  servlet:
    context-path: /

  port: 8881

spring:
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8

  # 配置数据库连接信息
  datasource:
    # local server configuration(Mysql)
    url: cdb-fqh1b3fq.bj.tencentcdb.com:10104/RSS?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: "root_RSS"
    driver-class-name: com.mysql.jdbc.Driver

      # local server configuration(Sql Server)
      # url: jdbc:sqlserver://139.198.19.162:1433;DatabaseName=device_status_db
      # url: jdbc:sqlserver://localhost:1433;DatabaseName=device_status_db?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
      # river-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      # username: "sa"
      # password: "Bjpv2017"

    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 86400

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.configuration.ImprovedNamingStrategy

    database-platform: org.hibernate.dialect.MySQL5Dialect

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
    cache: false